name: 'cardano_shared'
version: '1.0.0'
config-version: 2

profile: 'cardano_insights'

model-paths: ["models"]
seed-paths: ["seeds"]  
macro-paths: ["macros"]

models:
  cardano_shared:
    materialized: table