version: 2

sources:
  - name: lido_raw
    description: "Raw Catalyst data from Lido Nation API extraction"
    tables:
      - name: funds
        description: "Catalyst funding rounds from API"
        columns:
          - name: id
            description: "Unique fund identifier"
            tests:
              - unique
              - not_null
          - name: title
            description: "Fund title (e.g., 'Fund 13')"
      
      - name: proposals
        description: "Catalyst proposals from API"
        columns:
          - name: id
            description: "Unique proposal identifier" 
            tests:
              - unique
              - not_null
          - name: fund_id
            description: "Foreign key to funds table"
            tests:
              - not_null
          - name: title
            description: "Proposal title"
            tests:
              - not_null