cardano_insights:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: './cardano_insights.duckdb'
      threads: 4
      extensions:
        - httpfs
        - parquet

tech_intel:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: './tech_intel.duckdb'
      threads: 8