version: 2

sources:
  # Catalyst official fund results
  - name: official
    description: "Official Catalyst fund results from Google Sheets"  
    schema: official
    tables:
      - name: results
        description: "Official voting results and funding decisions"

  # GitHub data from API
  - name: github
    description: "GitHub trend data from API"
    schema: github
    tables:
      - name: stg_github_pull_requests
        description: "GitHub pull requests from API"
      - name: stg_github_releases
        description: "GitHub releases from API"
      - name: stg_github_repositories
        description: "GitHub repository metadata from API"

  # Lido data from API
  - name: lido
    description: "Lido Catalyst data from API"
    schema: lido
    tables:
      - name: proposals
        description: "Lido proposals from API"
      - name: funds
        description: "Lido funds from API"