name: 'dbt_catalyst'
version: '1.0.0'
profile: 'tech_intel'
config-version: 2

model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']
target-path: 'target'
clean-targets: ['target']

models:
  dbt_catalyst:
    +schema: 'silver'
    catalyst:
      +materialized: view
    map:
      +schema: 'map'
      +materialized: view
    gold:
      +schema: 'gold'
      +materialized: view