version: 2

models:
  # Bronze layer
  - name: stg_github_pull_requests
    description: Raw GitHub pull requests data from dlt
    columns:
      - name: id
        description: Unique GitHub pull request ID
        tests:
          - not_null
          - unique

  - name: stg_github_releases
    description: Raw GitHub releases data from dlt
    columns:
      - name: id
        description: Unique GitHub release ID
        tests:
          - not_null
          - unique

  - name: stg_github_repositories
    description: Raw GitHub repository metadata from dlt
    columns:
      - name: id
        description: Unique GitHub repository ID
        tests:
          - not_null
          - unique

  # Silver layer
  - name: stg_pull_requests
    description: Cleaned and enriched pull requests with feature classification
    columns:
      - name: repository
        description: Repository name in owner/repo format
        tests:
          - not_null
      - name: number
        description: Pull request number
        tests:
          - not_null
      - name: feat_classifier
        description: Automated feature classification of the pull request
        tests:
          - not_null
          - accepted_values:
              values: ['bug fix', 'feature', 'refactor', 'test', 'documentation', 'not clear']

  - name: stg_releases
    description: Cleaned and enriched releases data
    columns:
      - name: repository
        description: Repository name in owner/repo format
        tests:
          - not_null
      - name: tag
        description: Release tag name
        tests:
          - not_null
      - name: row_num
        description: Row number for deduplication, 1 = most recent
        tests:
          - not_null